#pragma once

#include "Core/EntryPoint.hpp"

#include "Core/HartApplication.hpp"
#include "Core/Assert.hpp"
#include "Core/Window.hpp"
#include "Core/Layer.hpp"
#include "Core/LayerStack.hpp"

#include "Graphics/Shader.hpp"
#include "Graphics/VertexBuffer.hpp"
#include "Graphics/IndexBuffer.hpp"
#include "Graphics/VertexArray.hpp"
#include "Graphics/Image.hpp"
#include "Graphics/Texture2D.hpp"
#include "Graphics/ShaderLibrary.hpp"
#include "Graphics/ParticleSystem.hpp"
#include "Graphics/Renderer/Colors.hpp"
#include "Graphics/Renderer/Renderer3D.hpp"
#include "Graphics/Renderer/Renderer2D.hpp"
#include "Graphics/Camera/OrthographicCamera.hpp"
#include "Graphics/Camera/OrthographicCameraController.hpp"
#include "Graphics/Camera/PerspectiveCamera.hpp"

#include "Maths/MathConstants.hpp"
#include "Maths/MathFunctions.hpp"
#include "Maths/Vec2.hpp"
#include "Maths/Vec3.hpp"
#include "Maths/Vec4.hpp"
#include "Maths/Mat4.hpp"

#include "Events/EventCategory.hpp"
#include "Events/Event.hpp"
#include "Events/WindowEvents.hpp"
#include "Events/WindowEvents.hpp"
#include "Events/MouseEvents.hpp"

#include "Inputs/KeyCodes.hpp"
#include "Inputs/MouseCodes.hpp"
#include "Inputs/InputManager.hpp"

#include "Utils/FileManager.hpp"
#include "Utils/Logger.hpp"
#include "Utils/Random.hpp"
#include "Utils/Timer.hpp"